name: ulink
description: uLINK.no for iOS, Android, Web, ... developed using Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2020.10.02+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  cloud_functions: ^0.6.0
  firebase_dynamic_links: ^0.6.0
  firebase_remote_config: ^0.4.0

  firebase_crashlytics: ^0.2.0
  # sentry is alternative to crashlytics
  sentry: ^3.0.1

  shared_preferences: ^0.5.12
  hive: ^1.4.4
  hive_flutter: ^0.3.1

  #apple_sign_in: ^0.1.0
  apple_sign_in:
    #path: ../../flutter-open-forks/flutter_apple_sign_in/
    git: git://github.com/beerstorm-net/flutter_apple_sign_in.git

  google_sign_in: ^4.5.4

  rxdart: ^0.24.1
  equatable: ^1.2.5
  # NB! v6.0.3 and higher is buggy!!
  #flutter_bloc: ^6.0.5
  flutter_bloc: 6.0.2
  data_connection_checker: ^0.3.4
  http: ^0.12.2
  uuid: ^2.2.2
  #logger: ^0.9.3
  logger:
    git: https://github.com/leisim/logger.git

  settings_ui: ^0.4.0
  #settings_ui:
  #  path: ../../flutter-open-forks/flutter-settings-ui/
  #git:
  #  url: git://github.com/yako-dev/flutter-settings-ui.git
  package_info: ^0.4.3
  device_info: ^0.4.2+8
  url_launcher: ^5.7.2
  jwt_decode: ^0.1.0

  country_icons: ^1.1.1
  flutter_icons: ^1.1.0

  share: ^0.6.5+2
  awesome_dialog: ^1.2.0
  flutter_spinkit: ^4.1.2+1
  dots_indicator: ^1.2.0
  #progress_dialog: ^1.2.4
  progress_dialog:
    #path: ../../flutter-open-forks/progress_dialog
    git: git://github.com/beerstorm-net/progress_dialog.git
  #jiffy: ^3.0.1
  jiffy:
    #path: ../../flutter-open-forks/jiffy/
    git: git://github.com/beerstorm-net/jiffy.git

  flutter_slidable: ^0.5.7
  clipboard: ^0.1.2+8
  pull_to_refresh: ^1.6.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app/app_icon.jpg"

# https://pub.dev/packages/flutter_native_splash
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/app/app_splash.jpg
  color: "ffffff"
  ios: true
  android: true
  fill: true


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/config/
    - assets/lang/
    - assets/images/
    - assets/images/app/
    - assets/images/onboarding_carousel_bg/
    - assets/images/onboarding_images/
    - assets/images/social_icons/

  fonts:
    - family: Sancreek
      fonts:
        - asset: assets/fonts/Sancreek-Regular.ttf
